# Import Statements

In [1]:
import pandas as pd
import json
import numpy as np
import pickle

from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.model_selection import cross_val_predict

# Loading the files created during the Data Preparation Step

In [2]:
x = open('Xfile_final.pkl','rb')
X_all = pickle.load(x)
x.close()
y = open('Yfile_final.pkl','rb')
Y_all = pickle.load(y)
y.close()

# Reshaping the The Data 

In [3]:
print(X_all.shape)
X_final = X_all.reshape(415,-1)
print(X_final.shape)

(415, 232, 12)
(415, 2784)


# Scaling the Data

In [4]:
scaler = StandardScaler()
scaler.fit(X_final)
scaled_x = scaler.transform(X_final)

# Using GridSearch to Determine the Best HyperParameter Configuration

In [5]:
parameters = {
    "kernel": ['rbf','poly'],
    "C": [1,10,10,100,1000,2000],
    "max_iter": [1000,2000,3000,4000,5000]   
}

grid = GridSearchCV(SVC(gamma='scale', decision_function_shape='ovo'), parameters, cv=5, verbose=2)
grid.fit(scaled_x, Y_all)

Fitting 5 folds for each of 60 candidates, totalling 300 fits
[CV] C=1, kernel=rbf, max_iter=1000 ..................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................... C=1, kernel=rbf, max_iter=1000, total=   0.6s
[CV] C=1, kernel=rbf, max_iter=1000 ..................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s


[CV] ................... C=1, kernel=rbf, max_iter=1000, total=   0.6s
[CV] C=1, kernel=rbf, max_iter=1000 ..................................
[CV] ................... C=1, kernel=rbf, max_iter=1000, total=   0.6s
[CV] C=1, kernel=rbf, max_iter=1000 ..................................
[CV] ................... C=1, kernel=rbf, max_iter=1000, total=   0.6s
[CV] C=1, kernel=rbf, max_iter=1000 ..................................
[CV] ................... C=1, kernel=rbf, max_iter=1000, total=   0.6s
[CV] C=1, kernel=rbf, max_iter=2000 ..................................
[CV] ................... C=1, kernel=rbf, max_iter=2000, total=   0.6s
[CV] C=1, kernel=rbf, max_iter=2000 ..................................
[CV] ................... C=1, kernel=rbf, max_iter=2000, total=   0.6s
[CV] C=1, kernel=rbf, max_iter=2000 ..................................
[CV] ................... C=1, kernel=rbf, max_iter=2000, total=   0.6s
[CV] C=1, kernel=rbf, max_iter=2000 ..................................
[CV] .

[CV] .................. C=10, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=10, kernel=rbf, max_iter=3000 .................................
[CV] .................. C=10, kernel=rbf, max_iter=3000, total=   0.4s
[CV] C=10, kernel=rbf, max_iter=3000 .................................
[CV] .................. C=10, kernel=rbf, max_iter=3000, total=   0.4s
[CV] C=10, kernel=rbf, max_iter=3000 .................................
[CV] .................. C=10, kernel=rbf, max_iter=3000, total=   0.5s
[CV] C=10, kernel=rbf, max_iter=3000 .................................
[CV] .................. C=10, kernel=rbf, max_iter=3000, total=   0.5s
[CV] C=10, kernel=rbf, max_iter=3000 .................................
[CV] .................. C=10, kernel=rbf, max_iter=3000, total=   0.5s
[CV] C=10, kernel=rbf, max_iter=4000 .................................
[CV] .................. C=10, kernel=rbf, max_iter=4000, total=   0.5s
[CV] C=10, kernel=rbf, max_iter=4000 .................................
[CV] .

/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=1000 ................................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.4s
[CV] C=10, kernel=poly, max_iter=1000 ................................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=1000 ................................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=1000 ................................
[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=3000 ................................
[CV] .

/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=1000 ................................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.4s
[CV] C=10, kernel=poly, max_iter=1000 ................................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.4s
[CV] C=10, kernel=poly, max_iter=1000 ................................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=1000 ................................
[CV] ................. C=10, kernel=poly, max_iter=1000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.4s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.4s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=2000 ................................
[CV] ................. C=10, kernel=poly, max_iter=2000, total=   0.5s
[CV] C=10, kernel=poly, max_iter=3000 ................................
[CV] .

/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=1000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=1000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=1000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=1000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=1000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=2000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=2000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=2000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=2000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=2000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=2000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=2000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=2000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=2000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=2000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=3000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=3000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=3000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=3000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=3000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=3000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=3000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=3000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=3000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=3000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=4000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=4000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=4000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=4000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=100, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=4000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=5000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=5000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=5000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=5000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=100, kernel=poly, max_iter=5000 ...............................
[CV] ................ C=100, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=1000 ...............................
[CV] .

/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=1000, kernel=rbf, max_iter=1000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=1000, kernel=rbf, max_iter=1000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=1000, kernel=rbf, max_iter=1000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=1000, kernel=rbf, max_iter=1000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=1000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=1000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=1000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=1000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=1000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=3000 ...............................
[CV] ................ C=1000, kernel=rbf, max_iter=3000, total=   0.4s
[CV] C=1000, kernel=rbf, max_iter=3000 ...............................
[CV] .

/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=1000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=1000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=1000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=1000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=1000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=1000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=1000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=1000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=1000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=2000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=2000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=2000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=2000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=2000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=3000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=3000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=3000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=3000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=3000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=4000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=4000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=5000, total=   0.3s
[CV] C=1000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=1000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=1000, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=1000 ...............................
[CV] ................ C=2000, kernel=rbf, max_iter=1000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=2000, kernel=rbf, max_iter=1000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=2000, kernel=rbf, max_iter=1000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=2000, kernel=rbf, max_iter=1000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=1000 ...............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ................ C=2000, kernel=rbf, max_iter=1000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=2000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=2000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=2000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=2000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=2000 ...............................
[CV] ................ C=2000, kernel=rbf, max_iter=2000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=3000 ...............................
[CV] ................ C=2000, kernel=rbf, max_iter=3000, total=   0.4s
[CV] C=2000, kernel=rbf, max_iter=3000 ...............................
[CV] .

/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=1000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=1000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=1000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=1000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=1000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=1000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=1000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=1000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=1000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=2000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=2000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=2000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=2000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=2000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=2000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=3000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=3000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=3000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=3000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=3000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=3000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=2000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=2000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=2000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=4000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=4000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=4000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=4000, total=   0.4s
[CV] C=2000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=5000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=5000, total=   0.3s
[CV] C=2000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=2000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


[CV] ............... C=2000, kernel=poly, max_iter=5000, total=   0.4s
[CV] C=2000, kernel=poly, max_iter=5000 ..............................


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
[Parallel(n_jobs=1)]: Done 300 out of 300 | elapsed:  2.2min finished
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


[CV] ............... C=2000, kernel=poly, max_iter=5000, total=   0.3s


/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovo', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1, 10, 10, 100, 1000, 2000],
                         'kernel': ['rbf', 'poly'],
                         'max_iter': [1000, 2000, 3000, 4000, 5000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

# Identifying the Best HyperParameter Configuration

In [6]:
grid.best_params_

{'C': 1000, 'kernel': 'rbf', 'max_iter': 1000}

# Creating the Train and Test Split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(scaled_x, Y_all, test_size=0.3)
print("Training samples : {} Testing Samples : {}".format(X_train.shape, X_test.shape))

Training samples : (290, 2784) Testing Samples : (125, 2784)


# Training the Model

In [9]:
clf = SVC(kernel='rbf', C=1000, max_iter=1000, gamma='scale', decision_function_shape='ovo')
clf.fit(X_train,y_train)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='scale', kernel='rbf',
    max_iter=1000, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

# Evaluating the Model

In [10]:
y_pred = clf.predict(X_test)

In [11]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.98        21
           1       1.00      0.95      0.97        19
           2       0.67      0.82      0.74        17
           3       0.79      0.65      0.71        23
           4       0.90      0.86      0.88        22
           5       0.96      1.00      0.98        23

    accuracy                           0.88       125
   macro avg       0.88      0.88      0.88       125
weighted avg       0.88      0.88      0.88       125

[[21  0  0  0  0  0]
 [ 0 18  0  1  0  0]
 [ 0  0 14  3  0  0]
 [ 1  0  4 15  2  1]
 [ 0  0  3  0 19  0]
 [ 0  0  0  0  0 23]]


# Using Cross Validation to Evaluate the Model

In [12]:
y_all_pred = cross_val_predict(clf, scaled_x, Y_all, cv=10)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.

In [13]:
print(classification_report(Y_all, y_all_pred))
print(confusion_matrix(Y_all,y_all_pred))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93        71
           1       1.00      0.99      0.99        68
           2       0.82      0.89      0.85        65
           3       0.79      0.83      0.81        70
           4       0.94      0.83      0.88        70
           5       0.96      0.93      0.94        71

    accuracy                           0.90       415
   macro avg       0.90      0.90      0.90       415
weighted avg       0.90      0.90      0.90       415

[[67  0  1  2  0  1]
 [ 0 67  0  1  0  0]
 [ 0  0 58  6  1  0]
 [ 2  0  7 58  2  1]
 [ 2  0  5  4 58  1]
 [ 2  0  0  2  1 66]]


# Saving the Model

In [14]:
f = open('svm_ovo_model_rbf.pkl', 'wb')
pickle.dump(clf, f)
f.close()