# Import Statements

In [1]:
import pandas as pd
import json
import numpy as np
import pickle

from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.model_selection import cross_val_predict

# Loading the files created during the Data Preparation Step

In [2]:
x = open('Xfile_final.pkl','rb')
X_all = pickle.load(x)
x.close()
y = open('Yfile_final.pkl','rb')
Y_all = pickle.load(y)
y.close()

# Reshaping the The Data 

In [3]:
print(X_all.shape)
X_final = X_all.reshape(415,-1)
print(X_final.shape)

(415, 232, 12)
(415, 2784)


# Scaling the Data

In [4]:
scaler = StandardScaler()
scaler.fit(X_final)
scaled_x = scaler.transform(X_final)

# Creating the Train and Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(scaled_x, Y_all, test_size=0.3)
print("Training samples : {} Testing Samples : {}".format(X_train.shape, X_test.shape))

Training samples : (290, 2784) Testing Samples : (125, 2784)


# Training the Model

In [6]:
clf = svm.LinearSVC(C=100, max_iter=5000)
clf.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=100, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=5000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

# Evaluating the Model

In [7]:
y_pred = clf.predict(X_test)

In [8]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86        21
           1       1.00      0.80      0.89        30
           2       0.47      0.47      0.47        19
           3       0.57      0.65      0.60        20
           4       0.72      0.72      0.72        18
           5       0.60      0.71      0.65        17

    accuracy                           0.71       125
   macro avg       0.70      0.70      0.70       125
weighted avg       0.73      0.71      0.72       125

[[18  0  0  1  0  2]
 [ 1 24  3  0  0  2]
 [ 1  0  9  6  1  2]
 [ 0  0  4 13  2  1]
 [ 0  0  3  1 13  1]
 [ 1  0  0  2  2 12]]


# Using Cross Validation to Evaluate the Model

In [9]:
y_all_pred = cross_val_predict(clf, scaled_x, Y_all, cv=10)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [10]:
print(classification_report(Y_all, y_all_pred))
print(confusion_matrix(Y_all,y_all_pred))

              precision    recall  f1-score   support

           0       0.81      0.90      0.85        71
           1       0.97      0.82      0.89        68
           2       0.59      0.72      0.65        65
           3       0.58      0.53      0.55        70
           4       0.81      0.74      0.78        70
           5       0.77      0.77      0.77        71

    accuracy                           0.75       415
   macro avg       0.76      0.75      0.75       415
weighted avg       0.76      0.75      0.75       415

[[64  1  0  3  0  3]
 [ 4 56  4  1  1  2]
 [ 3  0 47 13  2  0]
 [ 4  0 21 37  3  5]
 [ 0  1  5  6 52  6]
 [ 4  0  2  4  6 55]]


# Saving the Model

In [11]:
f = open('svm_ovr_model_all.pkl', 'wb')
pickle.dump(clf, f)
f.close()